/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MaterialCatalogsRouteImport } from './routes/material-catalogs'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ExpenseCategoriesRouteImport } from './routes/expense-categories'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BatchPosRouteImport } from './routes/batch-pos'
import { Route as BankAccountsRouteImport } from './routes/bank-accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as ReportsProductionRouteImport } from './routes/reports.production'
import { Route as ReportsPoSummaryRouteImport } from './routes/reports.po-summary'
import { Route as ReportsDailyRouteImport } from './routes/reports.daily'
import { Route as ReportsAccountingRouteImport } from './routes/reports.accounting'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ReportsPoSummaryIndexRouteImport } from './routes/reports.po-summary.index'
import { Route as ReportsPoSummaryPoIdRouteImport } from './routes/reports.po-summary.$poId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialCatalogsRoute = MaterialCatalogsRouteImport.update({
  id: '/material-catalogs',
  path: '/material-catalogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseCategoriesRoute = ExpenseCategoriesRouteImport.update({
  id: '/expense-categories',
  path: '/expense-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchPosRoute = BatchPosRouteImport.update({
  id: '/batch-pos',
  path: '/batch-pos',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsRoute = BankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsProductionRoute = ReportsProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsPoSummaryRoute = ReportsPoSummaryRouteImport.update({
  id: '/po-summary',
  path: '/po-summary',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsDailyRoute = ReportsDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsAccountingRoute = ReportsAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => ReportsRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPoSummaryIndexRoute = ReportsPoSummaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsPoSummaryRoute,
} as any)
const ReportsPoSummaryPoIdRoute = ReportsPoSummaryPoIdRouteImport.update({
  id: '/$poId',
  path: '/$poId',
  getParentRoute: () => ReportsPoSummaryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/batch-pos': typeof BatchPosRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/expense-categories': typeof ExpenseCategoriesRoute
  '/expenses': typeof ExpensesRoute
  '/material-catalogs': typeof MaterialCatalogsRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/users': typeof UsersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/reports/accounting': typeof ReportsAccountingRoute
  '/reports/daily': typeof ReportsDailyRoute
  '/reports/po-summary': typeof ReportsPoSummaryRouteWithChildren
  '/reports/production': typeof ReportsProductionRoute
  '/orders/': typeof OrdersIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/po-summary/$poId': typeof ReportsPoSummaryPoIdRoute
  '/reports/po-summary/': typeof ReportsPoSummaryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/batch-pos': typeof BatchPosRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/expense-categories': typeof ExpenseCategoriesRoute
  '/expenses': typeof ExpensesRoute
  '/material-catalogs': typeof MaterialCatalogsRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/users': typeof UsersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/reports/accounting': typeof ReportsAccountingRoute
  '/reports/daily': typeof ReportsDailyRoute
  '/reports/production': typeof ReportsProductionRoute
  '/orders': typeof OrdersIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/reports/po-summary/$poId': typeof ReportsPoSummaryPoIdRoute
  '/reports/po-summary': typeof ReportsPoSummaryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/batch-pos': typeof BatchPosRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/expense-categories': typeof ExpenseCategoriesRoute
  '/expenses': typeof ExpensesRoute
  '/material-catalogs': typeof MaterialCatalogsRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/users': typeof UsersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/reports/accounting': typeof ReportsAccountingRoute
  '/reports/daily': typeof ReportsDailyRoute
  '/reports/po-summary': typeof ReportsPoSummaryRouteWithChildren
  '/reports/production': typeof ReportsProductionRoute
  '/orders/': typeof OrdersIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/po-summary/$poId': typeof ReportsPoSummaryPoIdRoute
  '/reports/po-summary/': typeof ReportsPoSummaryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank-accounts'
    | '/batch-pos'
    | '/categories'
    | '/customers'
    | '/expense-categories'
    | '/expenses'
    | '/material-catalogs'
    | '/payments'
    | '/products'
    | '/reports'
    | '/users'
    | '/orders/$orderId'
    | '/reports/accounting'
    | '/reports/daily'
    | '/reports/po-summary'
    | '/reports/production'
    | '/orders/'
    | '/reports/'
    | '/reports/po-summary/$poId'
    | '/reports/po-summary/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank-accounts'
    | '/batch-pos'
    | '/categories'
    | '/customers'
    | '/expense-categories'
    | '/expenses'
    | '/material-catalogs'
    | '/payments'
    | '/products'
    | '/users'
    | '/orders/$orderId'
    | '/reports/accounting'
    | '/reports/daily'
    | '/reports/production'
    | '/orders'
    | '/reports'
    | '/reports/po-summary/$poId'
    | '/reports/po-summary'
  id:
    | '__root__'
    | '/'
    | '/bank-accounts'
    | '/batch-pos'
    | '/categories'
    | '/customers'
    | '/expense-categories'
    | '/expenses'
    | '/material-catalogs'
    | '/payments'
    | '/products'
    | '/reports'
    | '/users'
    | '/orders/$orderId'
    | '/reports/accounting'
    | '/reports/daily'
    | '/reports/po-summary'
    | '/reports/production'
    | '/orders/'
    | '/reports/'
    | '/reports/po-summary/$poId'
    | '/reports/po-summary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankAccountsRoute: typeof BankAccountsRoute
  BatchPosRoute: typeof BatchPosRoute
  CategoriesRoute: typeof CategoriesRoute
  CustomersRoute: typeof CustomersRoute
  ExpenseCategoriesRoute: typeof ExpenseCategoriesRoute
  ExpensesRoute: typeof ExpensesRoute
  MaterialCatalogsRoute: typeof MaterialCatalogsRoute
  PaymentsRoute: typeof PaymentsRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  UsersRoute: typeof UsersRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-catalogs': {
      id: '/material-catalogs'
      path: '/material-catalogs'
      fullPath: '/material-catalogs'
      preLoaderRoute: typeof MaterialCatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense-categories': {
      id: '/expense-categories'
      path: '/expense-categories'
      fullPath: '/expense-categories'
      preLoaderRoute: typeof ExpenseCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-pos': {
      id: '/batch-pos'
      path: '/batch-pos'
      fullPath: '/batch-pos'
      preLoaderRoute: typeof BatchPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts': {
      id: '/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/bank-accounts'
      preLoaderRoute: typeof BankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/production': {
      id: '/reports/production'
      path: '/production'
      fullPath: '/reports/production'
      preLoaderRoute: typeof ReportsProductionRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/po-summary': {
      id: '/reports/po-summary'
      path: '/po-summary'
      fullPath: '/reports/po-summary'
      preLoaderRoute: typeof ReportsPoSummaryRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/daily': {
      id: '/reports/daily'
      path: '/daily'
      fullPath: '/reports/daily'
      preLoaderRoute: typeof ReportsDailyRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/accounting': {
      id: '/reports/accounting'
      path: '/accounting'
      fullPath: '/reports/accounting'
      preLoaderRoute: typeof ReportsAccountingRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/po-summary/': {
      id: '/reports/po-summary/'
      path: '/'
      fullPath: '/reports/po-summary/'
      preLoaderRoute: typeof ReportsPoSummaryIndexRouteImport
      parentRoute: typeof ReportsPoSummaryRoute
    }
    '/reports/po-summary/$poId': {
      id: '/reports/po-summary/$poId'
      path: '/$poId'
      fullPath: '/reports/po-summary/$poId'
      preLoaderRoute: typeof ReportsPoSummaryPoIdRouteImport
      parentRoute: typeof ReportsPoSummaryRoute
    }
  }
}

interface ReportsPoSummaryRouteChildren {
  ReportsPoSummaryPoIdRoute: typeof ReportsPoSummaryPoIdRoute
  ReportsPoSummaryIndexRoute: typeof ReportsPoSummaryIndexRoute
}

const ReportsPoSummaryRouteChildren: ReportsPoSummaryRouteChildren = {
  ReportsPoSummaryPoIdRoute: ReportsPoSummaryPoIdRoute,
  ReportsPoSummaryIndexRoute: ReportsPoSummaryIndexRoute,
}

const ReportsPoSummaryRouteWithChildren =
  ReportsPoSummaryRoute._addFileChildren(ReportsPoSummaryRouteChildren)

interface ReportsRouteChildren {
  ReportsAccountingRoute: typeof ReportsAccountingRoute
  ReportsDailyRoute: typeof ReportsDailyRoute
  ReportsPoSummaryRoute: typeof ReportsPoSummaryRouteWithChildren
  ReportsProductionRoute: typeof ReportsProductionRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsAccountingRoute: ReportsAccountingRoute,
  ReportsDailyRoute: ReportsDailyRoute,
  ReportsPoSummaryRoute: ReportsPoSummaryRouteWithChildren,
  ReportsProductionRoute: ReportsProductionRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankAccountsRoute: BankAccountsRoute,
  BatchPosRoute: BatchPosRoute,
  CategoriesRoute: CategoriesRoute,
  CustomersRoute: CustomersRoute,
  ExpenseCategoriesRoute: ExpenseCategoriesRoute,
  ExpensesRoute: ExpensesRoute,
  MaterialCatalogsRoute: MaterialCatalogsRoute,
  PaymentsRoute: PaymentsRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRouteWithChildren,
  UsersRoute: UsersRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
